### PR TITLE
Tox updates

### PR DESCRIPTION
**Pull request by EvaSDK**
A couple of changes to make it easier to check various configurations before submitting further changes. 

Please note that the sitepackages setting correspond to my local setup and is in no way mandatory to stay like this after merge. I have a local pypi where I pushed a pre-built PySide but couldn't do the same for PyQt4 which is why it is in this state. Also it shows how you could deal with it for non-linux plaforms if needed.

Also, some unittests fail with PyQt4 running with python3 and they started to return standard types and not the ones you had with python2 nor those exposed by PySide.

### CODE REVIEW

**Comment by EvaSDK** [comment]
Travis CI integration is showcased at https://travis-ci.org/EvaSDK/Ghost.py/branches
Note that most errors come from random stalls in WSGI response, I couldn't debug this issue up to now, I had @hugokernel to have a look too but nothing to report on that front yet.

**Comment by jeanphix** [comment]
:+1: Need rebase

**Comment by EvaSDK** [comment]
Rebased. I'll push patches for Travis CI support as a separate PR if that's ok.

**Comment by jeanphix** [comment]
:+1:

**Pull request merged**
