### PR TITLE
Python 3.4 (backwards compatible)

### PR DESCRIPTION
**Pull request by sebmos**
All tests still execute correctly - one had to be modified a bit to support the unicode handling encoding changes in Python 3, plus several minor changes.
Let me know if there are any questions or if you're looking for clarification/improvements or want additional tests etc.

### CODE REVIEW

**Comment by mgrandi** [comment]
If you could update the package on pypi to contain this fix (as i just ran into this problem, with cookiejar being in a different package in python 3) that would be fantastic =)

**Comment by jeanphix** [comment]
Done.

**Comment by mgrandi** [comment]
Sorry to be a bother, but it seems you didn't push the right version to pypi? the `ghost.py` file is still the old version without the fixes in this pull request!

**Comment by jeanphix** [comment]
Oups, sorry, fixed.

**Pull request merged**
